app_version: 2.2.14
capabilities: []
categories:
- productivity
changelog_url: https://miniflux.app/releases.html
date_added: '2025-03-31'
description: Miniflux is a minimalist and opinionated feed reader.
home: https://miniflux.app
host_mounts: []
icon: https://media.sys.truenas.net/apps/outline/icons/icon.png
keywords:
- rss
- news
lib_version: 2.1.57
lib_version_hash: 6659ad369fff2f1df318cb6353bb32bffe7047dc21df4823750d39be7284e605
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: miniflux
run_as_context:
- description: Miniflux runs as non-root user.
  gid: 1001
  group_name: miniflux
  uid: 1001
  user_name: miniflux
- description: Postgres runs as non-root user.
  gid: 999
  group_name: postgres
  uid: 999
  user_name: postgres
screenshots: []
sources:
- https://miniflux.app/
- https://github.com/miniflux/v2
title: Miniflux
train: community
version: 1.0.0
