images:
  image:
    repository: miniflux/miniflux
    tag: 2.2.14
  postgres_17_image:
    repository: postgres
    tag: 17.6-bookworm
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.0.4

consts:
  miniflux_container_name: miniflux
  cron_container_name: cron
  postgres_container_name: postgres
  perms_container_name: permissions
  db_user: miniflux
  db_name: miniflux
  run_as_user: 1001
  run_as_group: 1001
