resources:
  limits:
    cpus: 2.0
    memory: 4096

ci: true
miniflux:
  postgres_image_selector: postgres_17_image
  admin_username: admin
  admin_password: password
  db_password: secret
  # oidc_auth:
  #   enabled: false
  #   client_id: ""
  #   client_secret: ""
  #   auth_uri: ""
  #   token_uri: ""
  #   userinfo_uri: ""
  #   logout_uri: ""
  #   username_claim: ""
  #   display_name: ""
  #   scopes: []
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  postgres_data: /opt/tests/mnt/miniflux/postgres_data

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
